import '/backend/supabase/supabase.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'package:flutter/material.dart';

Future enciarPedidoWhatsApp(BuildContext context) async {
  await launchURL('https://wa.me/244953173980');
}
